language: java
jdk:
- oraclejdk7
sudo: false
env:
  global:
    - TWILIO_ACCOUNT_SID=YOUR-TWILIO-ACCOUNT-SID
    - TWILIO_AUTH_TOKEN=YOUR-TWILIO-AUTH-TOKEN
    - TWILIO_PHONE_NUMBER=YOUR-TWILIO-PHONE-NUMBER
